### ISSUE TITLE
Error when try to remove role from project

### ISSUE THREAD

**Issue by Aliaksandrzaz** [turbomates/easybreezy#53]
Method: POST
Type: RAW
URL: localhost:3000/api/projects/{project-slug}/roles/{role-id}/remove

https://easybreezy.tmsoft.dev/api/projects/test/roles/0859f8c7-f973-4f57-960f-1e6aa7c57afd/remove
Responce {
    "message": "Something is wrong"
}
Status: 503

**Comment by shustrik** [comment]
@Aliaksandrzaz  fixed
